### ISSUE TITLE
Recent commit for CSRF breaks SDK when used in node

### ISSUE THREAD

**Issue by jamespedid** [camunda/camunda-bpm-sdk-js#33]
The following commit is breaking the http client for those who use the SDK in node:

https://github.com/camunda/camunda-bpm-sdk-js/commit/501705dbc16d2a43a670044f5a707c45443f53b8#diff-3fb897b73c45f2d1378d1bfa9d61a482

I'd appreciate it if you could fix this. In particular, document is not defined when using node because node has no notion of a document.

```
7/3/2018 10:31:40 AMTue, 03 Jul 2018 14:31:40 GMT @complion:chili:src:middlewares:apollo:index ReferenceError: document is not defined
7/3/2018 10:31:40 AM    at cookies (/app/node_modules/camunda-bpm-sdk-js/lib/api-client/http-client.js:42:3)
7/3/2018 10:31:40 AM    at prepareRequestHeaders (/app/node_modules/camunda-bpm-sdk-js/lib/api-client/http-client.js:66:16)
7/3/2018 10:31:40 AM    at HttpClient.load (/app/node_modules/camunda-bpm-sdk-js/lib/api-client/http-client.js:168:17)
7/3/2018 10:31:40 AM    at HttpClient.get (/app/node_modules/camunda-bpm-sdk-js/lib/api-client/http-client.js:154:15)
7/3/2018 10:31:40 AM    at Function.getByKey (/app/node_modules/camunda-bpm-sdk-js/lib/api-client/resources/process-definition.js:117:24)
7/3/2018 10:31:40 AM    at CamundaConnector.getProcessDefinition (/app/src/gql/connectors/camunda.js:350:48)
7/3/2018 10:31:40 AM    at FormLoader.loadProcessForm (/app/src/gql/models/workflow/FormLoader.js:28:65)
7/3/2018 10:31:40 AM    at FormLoader.getForm (/app/src/gql/models/workflow/FormLoader.js:17:29)
7/3/2018 10:31:40 AM    at WorkflowManager.getForm (/app/src/gql/models/workflow/WorkflowManager.js:31:33)
7/3/2018 10:31:40 AM    at getForm (/app/src/gql/schema/queries/resolvers/form.js:22:28)
7/3/2018 10:31:40 AM    at resolveFieldValueOrError (/app/node_modules/graphql/execution/execute.js:498:12)
7/3/2018 10:31:40 AM    at resolveField (/app/node_modules/graphql/execution/execute.js:462:16)
7/3/2018 10:31:40 AM    at /app/node_modules/graphql/execution/execute.js:311:18
7/3/2018 10:31:40 AM    at Array.reduce (<anonymous>)
7/3/2018 10:31:40 AM    at executeFields (/app/node_modules/graphql/execution/execute.js:308:42)
7/3/2018 10:31:40 AM    at executeOperation (/app/node_modules/graphql/execution/execute.js:236:122)
7/3/2018 10:31:40 AM    at executeImpl (/app/node_modules/graphql/execution/execute.js:133:26)
7/3/2018 10:31:40 AM    at Object.execute (/app/node_modules/graphql/execution/execute.js:110:229)
7/3/2018 10:31:40 AM    at doRunQuery (/app/node_modules/apollo-server-core/dist/runQuery.js:122:42)
7/3/2018 10:31:40 AM    at /app/node_modules/apollo-server-core/dist/runQuery.js:21:56
7/3/2018 10:31:40 AM    at <anonymous>
7/3/2018 10:31:40 AM    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by romansmirnov** [comment]
It should be fixed now.
